In [2]:
import pandas as pd

df = pd.read_csv("Students_exams_error.csv")
df

     gender math score  reading score  writing score
0    female         72           72.0           74.0
1       NaN         69           90.0           88.0
2    female         90           95.0           93.0
3      male         47            NaN           44.0
4      male        abc            NaN           75.0
..      ...        ...            ...            ...
995  female         88           99.0           95.0
996    male         62           55.0           55.0
997  female         59           71.0           65.0
998  female         68           78.0           77.0
999  female         77           86.0           86.0

[1000 rows x 4 columns]

In [3]:
df.isnull()

     gender  math score  reading score  writing score
0     False       False          False          False
1      True       False          False          False
2     False       False          False          False
3     False       False           True          False
4     False       False           True          False
..      ...         ...            ...            ...
995   False       False          False          False
996   False       False          False          False
997   False       False          False          False
998   False       False          False          False
999   False       False          False          False

[1000 rows x 4 columns]

In [4]:
df.isnull().sum()

gender           2
math score       0
reading score    3
writing score    3
dtype: int64

In [5]:
for col in df[["math score","reading score","writing score"]]:
    df [col] =pd.to_numeric(df[col],errors="coerce")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   gender         998 non-null    object
 1   math score     998 non-null    float64
 2   reading score  997 non-null    float64
 3   writing score  997 non-null    float64
dtypes: float64(3), object(1)
memory usage: 31.4+ KB

In [6]:
df.head()

   gender  math score  reading score  writing score
0  female        72.0           72.0           74.0
1     NaN        69.0           90.0           88.0
2  female        90.0           95.0           93.0
3    male        47.0            NaN           44.0
4    male         NaN            NaN           75.0

In [7]:
for col in df[['math score','reading score','writing score']]:
    df[col].fillna(value = df[col].mean(), inplace = True)
    
df.head(20)

C:\Users\moham\AppData\Local\Temp\ipykernel_11268\4020410569.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(value = df[col].mean(), inplace = True)

    gender  math score  reading score  writing score
0   female   72.000000      72.000000      74.000000
1      NaN   69.000000      90.000000      88.000000
2   female   90.000000      95.000000      93.000000
3     male   47.000000      69.158475      44.000000
4     male   66.081162      69.158475      75.000000
5   female   71.000000      69.158475     500.000000
6   female   88.000000      95.000000      92.000000
7      NaN   40.000000      43.000000      39.000000
8     male   66.081162      64.000000      67.000000
9   female   38.000000      60.000000      50.000000
10    male   58.000000      54.000000      68.814443
11    male   40.000000      52.000000      43.000000
12  female   65.000000      81.000000     400.000000
13    male   78.000000      72.000000      70.000000
14  female   50.000000      53.000000      58.000000
15  female   69.000000      75.000000      78.000000
16    male   88.000000      89.000000      86.000000
17  female   18.000000      32.000000      28.000000
18    male   46.000000      42.000000      46.000000
19  female   54.000000      58.000000      61.000000